name: Dexterity
version: 1.4.0
author: c7dev
main: me.c7dev.dexterity.Dexterity
api-version: 1.19
load: POSTWORLD
softdepend: [WorldEdit]

commands:
  dex:
    aliases: [d, dexterity, dx]
    description: Dexterity main command
    
permissions:
  dexterity.click:
    description: Required for the engine to calculate whether a player clicked a display (such as for attached commands)
  dexterity.build:
    description: Ability to place or break a block display and click with the worldedit wand
  dexterity.select.unowned:
    description: Ability for player to select a display that they do not own
  dexterity.admin:
    description: Access to debug commands or actions that should only be given to admins
  dexterity.maxvolume.\#:
    description: Replace \# with a number to set a maximum volume or entity selection count
  dexterity.command.*:
    description: Access the /d command
    children:
      dexterity.command: true
      dexterity.command.move: true
      dexterity.command.axis: true
      dexterity.command.clone: true
      dexterity.command.cmd: true
      dexterity.command.consolidate: true
      dexterity.command.convert: true
      dexterity.command.deconvert: true
      dexterity.command.highlight: true
      dexterity.command.glow: true
      dexterity.command.list: true
      dexterity.command.merge: true
      dexterity.command.owner: true
      dexterity.command.save: true
      dexterity.command.recenter: true
      dexterity.command.remove: true
      dexterity.command.replace: true
      dexterity.command.rotate: true
      dexterity.command.seat: true
      dexterity.command.scale: true
      dexterity.command.tile: true
      dexterity.command.schematic.*: true
      dexterity.command.wand: true
  dexterity.command:
    description: Use /d select, /d undo, /d redo, /d help
  dexterity.command.move:
    description: Use /d move, /d align
  dexterity.command.axis:
    description: Use /d axis
  dexterity.command.clone:
    description: Use /d clone
  dexterity.command.cmd:
    description: Use /d cmd
  dexterity.command.cmd.console:
    description: Use /d cmd to add console commands
  dexterity.command.consolidate:
    description: Use /d consolidate
  dexterity.command.convert:
    description: Use /d convert
  dexterity.command.deconvert:
    description: Use /d deconvert
  dexterity.command.highlight:
    description: Use /d highlight #
  dexterity.command.glow:
    description: Use /d glow
  dexterity.command.list:
    description: Use /d list
  dexterity.command.merge:
    description: Use /d merge
  dexterity.command.owner:
    description: Use /d owner
  dexterity.command.save:
    description: Use /d save, /d unsave
  dexterity.command.recenter:
    description: Use /d recenter
  dexterity.command.remove:
    description: Use /d remove
  dexterity.command.replace:
    description: Use /d replace
  dexterity.command.rotate:
    description: Use /d rotate
  dexterity.command.scale:
    description: Use /d scale
  dexterity.command.seat:
    description: Use /d seat
  dexterity.command.tile:
    description: Use /d tile
  dexterity.command.wand:
    description: Use /d wand #
  dexterity.command.schematic:
    description: Use /d schem
  dexterity.command.schematic.*:
    description: Use all /d schem sub-commands
    children:
      dexterity.command.schematic.import: true
      dexterity.command.schematic.export: true
  dexterity.command.schematic.import:
    description: Use /d schem import
  dexterity.command.schematic.export:
    description: Use /d schem export
